title: "Legal Modernism"
languageCode: "en-us"
# baseURL: 'http://example.org/'

params:
  tagline: "American legal history through computational methods"
  description: "TODO"

markup:
  goldmark:
    renderer:
      unsafe: true

disableKinds:
  - "taxonomy"
  - "taxonomyTerm"

build:
  noJSConfigInAssets: true
